### ISSUE TITLE
Incompatible with Valkyrien Skies

### ISSUE THREAD

**Issue by hatkidchan** [Lortseam/completeconfig#27] opened 2024-03-20 17:33 UTC
Having completeconfig installed alongside Valkyrien Skies causes game to not start
 - Fabric 0.15.7 on Minecraft 1.20.1
 - CompleteConfig `2.5.0`
 - Let Sleeping Dogs Lie `1.2.0` (uses CompleteConfig, I could try with other mod that uses it too, but I don't know any other one)
 - Valkyrien Skies `2.1.3-beta.1` which has those bundled in it:
   - `cloth-config-fabric-11.1.106.jar`
   - `fabric-language-kotlin-1.10.10+kotlin.1.9.10.jar`
   - `mixinextras-fabric-0.2.0.jar`
 - Cloth Config `11.1.118`
 - Fabric Language Kotlin `1.10.19+kotlin.1.9.23`

<details>
<summary>Full mods list (long)</summary>

```
	- ae2 15.0.23
	   \-- team_reborn_energy 3.0.0
	- ae2cc 1.1.0.0-1.20.1-FABRIC
	- amecs 1.3.10+mc.1.20.1
	   \-- amecsapi 1.4.0+mc1.20-pre1
	- amendments 1.20-1.1.10
	   \-- mixinsquared 0.1.1
	- animal_feeding_trough 1.0.3+1.20.1
	- antique-atlas 1.4.3+1.20
	   \-- folk_sisby_kaleido-config 0.1.1+1.1.0-beta.3
	- anxff 1.4.0+1.20.1
	- appleskin 2.5.1+mc1.20
	- architectury 9.2.14
	- armorstands 1.2.1
	- athena 3.1.2
	- authme 7.0.2+1.20
	- badpackets 0.4.3
	- balm-fabric 7.2.2
	- beautify 1.1.0+1.20
	- betterclouds 1.3.16+1.20.1
	- betterpingdisplay 1.1.1
	- betterstats 3.9.4+fabric-1.20.1
	   \-- tcdcommons 3.9.3+fabric-1.20.1
	- bookshelf 20.1.9
	- botanypots 13.0.25
	- botarium 2.3.3
	   \-- team_reborn_energy 3.0.0
	- bounced 4.0.0
	- bushierflowers 0.0.3-1.20.1
	- c2me 0.2.0+alpha.11.5
	   |-- c2me-base 0.2.0+alpha.11.5
	   |-- c2me-client-uncapvd 0.2.0+alpha.11.5
	   |-- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.11.5
	   |-- c2me-fixes-general-threading-issues 0.2.0+alpha.11.5
	   |-- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.11.5
	   |-- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.11.5
	   |-- c2me-notickvd 0.2.0+alpha.11.5
	   |-- c2me-opts-allocs 0.2.0+alpha.11.5
	   |-- c2me-opts-chunk-access 0.2.0+alpha.11.5
	   |-- c2me-opts-chunkio 0.2.0+alpha.11.5
	   |-- c2me-opts-math 0.2.0+alpha.11.5
	   |-- c2me-opts-scheduling 0.2.0+alpha.11.5
	   |-- c2me-opts-worldgen-general 0.2.0+alpha.11.5
	   |-- c2me-opts-worldgen-vanilla 0.2.0+alpha.11.5
	   |-- c2me-rewrites-chunk-serializer 0.2.0+alpha.11.5
	   |-- c2me-rewrites-chunkio 0.2.0+alpha.11.5
	   |-- c2me-server-utils 0.2.0+alpha.11.5
	   |-- c2me-threading-chunkio 0.2.0+alpha.11.5
	   |-- c2me-threading-lighting 0.2.0+alpha.11.5
	   |-- c2me-threading-worldgen 0.2.0+alpha.11.5
	   |-- com_ibm_async_asyncutil 0.1.0
	   |-- net_objecthunter_exp4j 0.4.8
	   \-- org_threadly_threadly 7.0
	- carryon 2.1.2.7
	- cccbridge 1.6.2b-fabric
	- chat_heads 0.10.32
	- chatcalc 3.0.24
	- chatimage 1.2.3+1.20.1+fabric
	   |-- actionlib 0.6.1-fabric
	   \-- io_github_kituin_chatimagecode 0.9.5
	- chipped 3.0.4
	- chunkloaders 1.2.8+a
	- chunksending 1.20.1-2.8
	- clickthrough 1.20-fabric0.83.0-0.4.1
	   |-- crowdin-translate 1.4+1.19.3
	   \-- gbfabrictools 1.4+1.20
	- cloth-config 11.1.118
	   \-- cloth-basic-math 0.6.1
	- clutter 1.20-0.5.7
	- collective 7.40
	- colorfulsubtitles 1.3.0
	- completeconfig 2.5.0
	   |-- completeconfig-base 2.5.0
	   |-- completeconfig-gui-cloth 2.5.0
	   \-- completeconfig-gui-yacl 2.5.0
	- computer_cartographer 1.0
	- computercraft 1.109.7
	   |-- cc_tweaked_cobalt 0.9.1
	   |-- com_electronwill_night-config_core 3.6.7
	   |-- com_electronwill_night-config_toml 3.6.7
	   |-- com_jcraft_jzlib 1.1.3
	   |-- io_netty_netty-codec-http 4.1.82.Final
	   |-- io_netty_netty-codec-socks 4.1.82.Final
	   \-- io_netty_netty-handler-proxy 4.1.82.Final
	- continuity 3.0.0-beta.4+1.20.1
	- convenientdecor 0.4.1
	   \-- omega-config 1.4.0+1.20.1
	- copycats 1.20.1-1.2.2
	- crab 1.0.2
	- create 0.5.1-f-build.1335+mc1.20.1
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- flywheel 0.6.10-2
	   |-- milk 1.2.60
	   |    \-- dripstone_fluid_lib 3.0.2
	   |-- porting_lib_accessors 2.3.0+1.20.1
	   |    \-- porting_lib_core 2.3.0+1.20.1
	   |-- porting_lib_base 2.3.0+1.20.1
	   |    |-- porting_lib_attributes 2.3.0+1.20.1
	   |    |-- porting_lib_common 2.3.0+1.20.1
	   |    |-- porting_lib_core 2.3.0+1.20.1
	   |    |-- porting_lib_fluids 2.3.0+1.20.1
	   |    |-- porting_lib_lazy_registration 2.3.0+1.20.1
	   |    |-- porting_lib_mixin_extensions 2.3.0+1.20.1
	   |    |-- porting_lib_utility 2.3.0+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_brewing 2.3.0+1.20.1
	   |    \-- porting_lib_core 2.3.0+1.20.1
	   |-- porting_lib_client_events 2.3.0+1.20.1
	   |    \-- porting_lib_core 2.3.0+1.20.1
	   |-- porting_lib_entity 2.3.0+1.20.1
	   |    |-- porting_lib_core 2.3.0+1.20.1
	   |    \-- porting_lib_mixin_extensions 2.3.0+1.20.1
	   |-- porting_lib_extensions 2.3.0+1.20.1
	   |    |-- porting_lib_attributes 2.3.0+1.20.1
	   |    |-- porting_lib_common 2.3.0+1.20.1
	   |    |-- porting_lib_core 2.3.0+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_models 2.3.0+1.20.1
	   |    |-- porting_lib_core 2.3.0+1.20.1
	   |    |-- porting_lib_fluids 2.3.0+1.20.1
	   |    \-- porting_lib_model_loader 2.3.0+1.20.1
	   |-- porting_lib_networking 2.3.0+1.20.1
	   |    \-- porting_lib_core 2.3.0+1.20.1
	   |-- porting_lib_obj_loader 2.3.0+1.20.1
	   |    |-- porting_lib_core 2.3.0+1.20.1
	   |    \-- porting_lib_model_loader 2.3.0+1.20.1
	   |-- porting_lib_tags 3.0
	   |    \-- porting_lib_core 2.3.0+1.20.1
	   |-- porting_lib_tool_actions 2.3.0+1.20.1
	   |    \-- porting_lib_core 2.3.0+1.20.1
	   |-- porting_lib_transfer 2.3.0+1.20.1
	   |    |-- porting_lib_core 2.3.0+1.20.1
	   |    \-- porting_lib_fluids 2.3.0+1.20.1
	   |-- reach-entity-attributes 2.4.0
	   \-- registrate-fabric 1.3.62-MC1.20.1
	        |-- porting_lib_data 2.1.1090+1.20
	        |    \-- porting_lib_gametest 2.1.1090+1.20
	        \-- porting_lib_model_generators 2.1.1090+1.20
	             |-- porting_lib_gametest 2.1.1090+1.20
	             \-- porting_lib_model_materials 2.1.1090+1.20
	- create_enchantment_industry 1.2.16
	   \-- create_dragon_lib 1.4.2
	- create_new_age 1.1.2
	- createaddition 1.2.3
	- createdeco 2.0.1-1.20.1-fabric
	- createreibugfix 0.1.0-create0.5.1-mc1.20.x
	   \-- conditional-mixin 0.3.2
	- cupboard 1.20.1-2.6
	- dark-loading-screen 1.6.14
	- delightfulcreators 1.1.8
	- display_case 1.0.8
	- dogslie 1.2.0
	- dynamic_fps 3.4.2
	- enchdesc 17.0.14
	- entityculling 1.6.2-mc1.20.1
	- exordium 1.2.1-mc1.20.1
	- explorerscompass 1.20.1-2.2.3-fabric
	- extractinator 2.3.0
	- fabric-api 0.92.0+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.1+1802ada577
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.4+1802ada577
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabric-language-kotlin 1.10.19+kotlin.1.9.23
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.23
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.7
	   \-- mixinextras 0.3.5
	- fabrishot 1.10.1
	- fallingleaves 1.15.4
	- farmersdelight 1.20.1-1.4.3
	- fastipping 1.0.1
	- ferritecore 6.0.1
	- figura 0.1.4+1.20.1
	   |-- com_github_figuramc_luaj_luaj-core 3.0.8-figura
	   |-- com_github_figuramc_luaj_luaj-jse 3.0.8-figura
	   \-- com_neovisionaries_nv-websocket-client 2.14
	- fog-looks-good-now 2.2.0+1.20.1
	- forgeconfigapiport 8.0.0
	- garnished 1.7.4+1.20.1
	   |-- create_dragon_lib 1.4.2
	   \-- terraform-wood-api-v1 7.0.1
	- geckolib 4.4.4
	   \-- com_eliotlash_mclib_mclib 20
	- gentlepicking 1.1.0
	- givemehats 3.0.0
	   |-- cardinal-components-base 5.2.2
	   \-- cardinal-components-entity 5.2.2
	- glass_armor 1.0.0+1.20.x
	- gravity_changer_q 1.1.2
	- gravity_tricks 1.0-SNAPSHOT
	   |-- cardinal-components-base 5.2.2
	   |-- cardinal-components-block 5.2.2
	   |-- cardinal-components-chunk 5.2.2
	   |-- cardinal-components-entity 5.2.2
	   |-- cardinal-components-item 5.2.2
	   |-- cardinal-components-level 5.2.2
	   |-- cardinal-components-scoreboard 5.2.2
	   \-- cardinal-components-world 5.2.2
	- held-item-info 1.5.0
	- horseexpert 8.1.1
	- immersive_paintings 0.6.7+1.20.1
	- inventoryessentials 8.2.3
	- inventorymanagement 1.3.1
	- ironchests 5.0.2
	- jade 11.8.0
	- jadeaddons 5.2.3
	- jamlib 0.6.1+1.20.x
	- java 17
	- jump_sounds 1.4.3
	- kawaiidishes 1.11.1
	- kiwi 11.5.5
	- konkrete 1.8.1
	- krypton 0.2.3
	   \-- com_velocitypowered_velocity-native 3.2.0-SNAPSHOT
	- labellingcontainers 1.5.2
	- lambdynlights 2.3.2+1.20.1
	   |-- pride 1.2.0+1.19.4
	   \-- spruceui 5.0.0+1.20
	- lazydfu 0.1.3
	- lithium 0.11.2
	- luphieclutteredmod 2.1.0+1.20.1
	- luratagview 2001.0.0
	- make_bubbles_pop 0.2.0-fabric
	- many_flowers 1.20.1-1.5
	   |-- ducky-updater-lib 2023.10.1
	   \-- fstats-api 2023.11.2
	- melody 1.0.3
	- minecraft 1.20.1
	- mod-loading-screen 1.0.4
	   |-- com_formdev_flatlaf 3.0
	   \-- net_lenni0451_reflect 1.0.2
	- modelfix 1.14
	- modmenu 7.2.2
	- moonlight 1.20-2.11.4
	- morechathistory 1.3.0
	- morefrogs 1.20.1-1.2.5-fabric
	- mousetweaks 2.25
	- mru 0.4.0+1.20
	- nbt_ac 1.2
	- nbteditor 1.13.0
	- netherchested 8.0.3
	   \-- puzzlesapi 8.1.5
	        |-- cardinal-components-base 5.2.2
	        |-- cardinal-components-entity 5.2.2
	        \-- puzzlesaccessapi 8.0.9
	- nmuk 1.1.1+mc1.20.1
	- nochatreports 1.20.1-v2.2.2
	- nonarrator 1.0.1
	- notenoughcrashes 4.4.7+1.20.1
	- observable 4.4.1
	- particlerain 2.0.8
	- patpatpat 1.1.0
	- paxi 1.20-Fabric-4.0
	   \-- org_reflections_reflections 0.10.2
	- pickupnotifier 8.0.0
	- ping-wheel 1.8.0
	- plantinajar 2.5.3
	   |-- libgui 8.0.1+1.20
	   |    |-- jankson 5.0.1+j1.2.2
	   |    |    \-- blue_endless_jankson 1.2.2
	   |    \-- libninepatch 1.2.0
	   \-- org_objenesis_objenesis 3.2
	- plethora 1.10.6
	   |-- cloth-utils-v1 4.0.65
	   |-- com_typesafe_config 1.4.2
	   |-- io_leangen_geantyref_geantyref 1.3.13
	   |-- org_spongepowered_configurate-core 4.1.2
	   \-- org_spongepowered_configurate-hocon 4.1.2
	- polyeng 0.1.0-1.20.1
	- polymorph 0.49.1+1.20.1
	   \-- spectrelib 0.13.14+1.20.1
	- puzzleslib 8.1.18
	- quad 1.1.1
	- reacharound 1.1.2
	- recipe-book-is-pain 0.10.0-1.20.1
	   |-- dark-matter-base 1.0.0-1.20
	   |-- dark-matter-enums 1.0.0-1.20
	   |-- dark-matter-minecraft 1.0.0-1.20
	   \-- dark-matter-recipe-book 1.0.0-1.20
	- replaymod 1.20.1-2.6.15
	- resourcefulconfig 2.1.2
	- resourcefullib 2.1.23
	   |-- com_teamresourceful_bytecodecs 1.0.2
	   \-- com_teamresourceful_yabn 1.0.3
	- roughlyenoughitems 12.0.684
	   \-- error_notifier 1.0.9
	- sc-peripherals 1.8.4
	   |-- cloth-utils-v1 4.0.65
	   |-- io_prometheus_simpleclient 0.16.0
	   |-- io_prometheus_simpleclient_hotspot 0.16.0
	   |-- io_prometheus_simpleclient_httpserver 0.16.0
	   |-- org_cache2k_cache2k-api 2.6.1.Final
	   |-- org_cache2k_cache2k-core 2.6.1.Final
	   \-- sc-library 1.4.1
	- scarves 1.3.0
	   \-- pride 1.2.0+1.19.4
	- screenshotclipboard 1.0.9
	- seamless_loading_screen 2.0.3+1.20.1
	- seasonhud 1.7.15
	- seasons 2.3+1.20
	- servercore 1.3.9+1.20.1
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   \-- placeholder-api 2.1.2+1.20.1
	- serverpingerfixer 1.0.4
	- shifty-hotbar 1.1
	- shulkerboxtooltip 4.0.4+1.20.1
	- sit 1.20-24
	- skinlayers3d 1.6.2
	- smoke_suppression 1.0.16
	   \-- crowdin-translate 1.4+1.19.3
	- smoothswapping 0.9.3.1
	- snowrealmagic 10.4.1
	- spellchecker 3.0.1
	   \-- com_swabunga_jazzy 1.0.0
	- structureessentials 1.20.1-3.3
	- supermartijn642configlib 1.1.8+a
	- supermartijn642corelib 1.1.17
	- supplementaries 1.20-2.8.4
	   \-- mixinsquared 0.1.1
	- symbol-chat 1.20.1-1.1.2
	- taxfreelevels 1.3.9
	- tempad 2.3.3
	- textile_backup 3.1.2-1.20
	   |-- com_github_shevek_parallelgzip af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6
	   |-- org_apache_commons_commons-compress 1.22
	   \-- org_tukaani_xz 1.9
	- toms_peripherals 1.2.0
	- tooltipfix 1.1.1-1.20
	- travelersbackpack 1.20.1-9.1.9
	- trinkets 3.7.2
	- valkyrienskies 2.1.3-beta.1
	- variantvanillablocks 1.3.8
	- visuality 0.7.1+1.20
	- visualworkbench 8.0.0
	- vt_downloader 2.0.8+1.20.1
	- windchimes 1.2.4+1.20
	- winterly 0.9.3+1.20
	- xaerominimap 24.0.2
	- xaeroworldmap 1.38.1
	- yet_another_config_lib_v3 3.2.2+1.20
	   |-- com_twelvemonkeys_common_common-image 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-io 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-lang 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0-SNAPSHOT
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1
	- yungsapi 1.20-Fabric-4.0.4
	   \-- org_javassist_javassist 3.29.2-GA
	- zoomify 2.11.2
	   |-- com_akuleshov7_ktoml-core-jvm 0.4.1
	   |-- dev_isxander_settxi_settxi-core 2.10.6
	   \-- dev_isxander_settxi_settxi-kotlinx-serialization 2.10.6
```
</details>

<details>
<summary>Traceback</summary>

```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'dogslie'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at fudge.notenoughcrashes.fabric.mixinhandlers.ModLoaders.fabricEntrypoints(ModLoaders.java:9)
	at net.minecraft.class_310.redirect$fbh000$notenoughcrashes$catchFabricInit(class_310.java:23506)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NoSuchMethodError: 'java.lang.Object[] org.apache.commons.lang3.ArrayUtils.addFirst(java.lang.Object[], java.lang.Object)'
	at me.lortseam.completeconfig.data.ConfigOptions.lambda$createDefaultLoader$2(ConfigOptions.java:74)
	at me.lortseam.completeconfig.data.ConfigOptions.createLoader(ConfigOptions.java:96)
	at me.lortseam.completeconfig.data.ConfigOptions.createDefaultLoader(ConfigOptions.java:72)
	at me.lortseam.completeconfig.data.Config.<init>(Config.java:49)
	at me.lortseam.completeconfig.data.Config.<init>(Config.java:67)
	at me.ichun.mods.dogslie.loader.fabric.LoaderFabricClient.onInitializeClient(LoaderFabricClient.java:18)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 11 more
```
</details>

I have a suspicion that it could be caused by Valkyrien Skies bundling clothconfig or fabric-language-kotlin in itself, but I have no way of confirming that.

Weird part is that VS is not mentioned anywhere in the traceback, I found that out by carefully removing mods one by one until I found that it was the cause

**Comment by abidbmt** [comment] 2024-04-30 04:58
Same crash, I also have valkyrien skies installed

**Comment by Poopooracoocoo** [comment] 2024-05-11 03:37
https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/617

**Comment by Lortseam** [comment] 2024-07-04 19:48
> [ValkyrienSkies/Valkyrien-Skies-2#617](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/617)

This is the cause of this issue and has to be fixed by the developer of Valkyrien Skies.

**Closed as completed by Lortseam** 2024-07-04 19:48 UTC
